module.exports = {

    // requiest errors
    REQUEST_PASSWORD_REQUIRED: 'REQUEST_PASSWORD_REQUIRED',
    REQUEST_PASSWORD_WRONG: 'REQUEST_PASSWORD_WRONG',
    REQUEST_TOKEN_REQUIRED: 'REQUEST_TOKEN_REQUIRED',
    REQUEST_TOKEN_WRONG: 'REQUEST_TOKEN_WRONG',
    REQUEST_BASE64_WRONG: 'REQUEST_BASE64_WRONG',
    REQUEST_RECORD_EXIST: 'REQUEST_RECORD_EXIST',
    REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
    REQUEST_EXIST: 'REQUEST_EXISt',

    // database errors
    DB_MONGOOSE_ON_SAVE: 'DB_MONGOOSE_ON_SAVE',
    DB_MONGOOSE_ON_FIND: 'DB_MONGOOSE_ON_FIND',
    DB_MONGOOSE_ON_FIND_AND_UPDATE: 'DB_MONGOOSE_ON_FIND_AND_UPDATE',
    DB_MONGOOSE_ON_CREATE: 'DB_MONGOOSE_ON_CREATE',

    // fs errors
    FS_ACCESS_W: 'FS_ACCESS_W',
    FS_ACCESS_R: 'FS_ACCESS_R',

    // mailgun error
    MAILGUN_RESPONSE_DISCARD: 'MAILGUN_RESPONSE_DISCARD',

    // permission errors
    PERMISSION_NOT_ROOT_USER: 'PERMISSION_NOT_ROOT_USER',

    // validation errors
    VALIDATE_PASSWORD_REQUIRED: 'VALIDATE_PASSWORD_REQUIRED',
    VALIDATE_PASSWORD_SHORT: 'VALIDATE_PASSWORD_SHORT',
    VALIDATE_PASSWORD_INVALID: 'VALIDATE_PASSWORD_INVALID',
    VALIDATE_EMAIL_REQUIRED: 'VALIDATE_EMAIL_REQUIRED',
    VALIDATE_EMAIL_INVALID: 'VALIDATE_EMAIL_INVALID',
    VALIDATE_NAME_REQUIRED: 'VALIDATE_NAME_REQUIRED',
}
